FROM python:3.11-alpine AS base

RUN apk update && apk add git py3-pyarrow bash

WORKDIR /api
COPY api/requirements_alpine.txt ./
RUN pip3 install -r requirements_alpine.txt

COPY api ./

EXPOSE 5000

ENV PORT 5000
# set hostname to localhost
ENV VIPDOC_PATH /vipdoc
ENV QUANT_EXCAHNGE_MODULE_PATH /api/modules
ENV QUANT_EXCAHNGE_DATA_PATH /data
ENV PYTHONPATH /usr/lib/python3.11/site-packages

CMD ["python3", "-m", "flask", "--app", "src/quant_exchange", "run", "--host=0.0.0.0"]
