FROM python:3.11-slim AS base

RUN apt update && apt install -y git gcc

WORKDIR /api
COPY api/requirements.txt ./
RUN pip3 install -r requirements.txt

COPY api ./

EXPOSE 5000

ENV PORT=5000
# set hostname to localhost
ENV VIPDOC_PATH=/vipdoc
ENV QUANT_EXCAHNGE_MODULE_PATH=/api/modules
ENV QUANT_EXCAHNGE_DATA_PATH=/data

CMD ["python3", "-m", "flask", "--app", "src/quant_exchange", "run", "--host=0.0.0.0"]
